#!/usr/bin/env bash
# EcoSeek Frontend — quick start via Docker (no-broker stack).
# Works on Linux, macOS, and Windows (WSL / Git Bash).
#
# The frontend is a static React SPA served by nginx. Chat requests are
# proxied SERVER-SIDE by nginx to the Emily Hermes gateway on host port
# 8642 — the browser never sees an API key. emily/nginx.conf is templated
# with EMILY_HERMES_KEY at BUILD time and the frontend Dockerfile refuses
# to build if that build-arg is empty, so this script loads the key from
# .env (EMILY_HERMES_KEY, falling back to EMILY_API_KEY) or generates a
# fresh random one and appends it to .env.
#
# Usage:
#   bash frontend-start.sh                                    # default: self-hosted Emily via nginx
#   REACT_APP_EMILY_URL=http://localhost:8642 bash frontend-start.sh  # point the SPA at the gateway directly
#   FRONTEND_PORT=9080 bash frontend-start.sh                 # custom port
#
# No Node.js or npm required — only Docker.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

CONTAINER_NAME="ecoseek-frontend"
IMAGE_NAME="ecoseek-frontend"

info()  { printf "${GREEN}[ecoseek]${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}[ecoseek]${NC} %s\n" "$*"; }
error() { printf "${RED}[ecoseek]${NC} %s\n" "$*" >&2; }

# ── Prerequisites ─────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  error "Docker is not installed. Get it at: https://docs.docker.com/get-docker/"
  exit 1
fi

if ! docker info &>/dev/null 2>&1; then
  error "Docker daemon is not running. Start Docker Desktop and try again."
  exit 1
fi

# ── Configuration ─────────────────────────────────────────────────────
PORT="${FRONTEND_PORT:-4000}"
# Default: the SPA talks to itself on this port; nginx proxies /v1/* to
# the Emily gateway on :8642 with the key injected server-side.
EMILY_URL="${REACT_APP_EMILY_URL:-http://localhost:${PORT}}"

# EMILY_HERMES_KEY is a REQUIRED build arg (frontend/Dockerfile aborts the
# build if it is empty). Prefer an existing value: shell env > .env
# (EMILY_HERMES_KEY > EMILY_API_KEY). Otherwise generate a stable random
# one and persist it to .env so future rebuilds reuse the same key.
ENV_EMILY_KEY=""
ENV_API_KEY=""
if [ -f .env ]; then
  ENV_EMILY_KEY="$(grep -E '^EMILY_HERMES_KEY=' .env 2>/dev/null | head -1 | cut -d= -f2- || true)"
  ENV_API_KEY="$(grep -E '^EMILY_API_KEY=' .env 2>/dev/null | head -1 | cut -d= -f2- || true)"
fi
EMILY_HERMES_KEY="${EMILY_HERMES_KEY:-${ENV_EMILY_KEY:-${ENV_API_KEY:-}}}"
if [ -z "${EMILY_HERMES_KEY}" ]; then
  warn "No EMILY_HERMES_KEY / EMILY_API_KEY found in environment or .env — generating one."
  EMILY_HERMES_KEY="$(openssl rand -hex 24 2>/dev/null || head -c 24 /dev/urandom | od -An -tx1 | tr -d ' \n')"
  if [ -f .env ]; then
    printf '\n# Shared frontend ↔ Emily gateway secret (generated by frontend-start.sh)\nEMILY_HERMES_KEY=%s\n' "$EMILY_HERMES_KEY" >> .env
    chmod 600 .env || true
    info "Appended EMILY_HERMES_KEY to .env"
  else
    warn "No .env found — the key is used for this build only."
  fi
fi

# Same canonical key authenticates the SPA (build-time bake-in); nginx
# always overwrites the Authorization header with the server-side
# EMILY_HERMES_KEY value, so the browser token never reaches Emily.
EMILY_KEY="${REACT_APP_EMILY_KEY:-${EMILY_HERMES_KEY}}"

info "Building EcoSeek frontend..."
info "  Emily URL:    $EMILY_URL"
info "  Local port:   $PORT"
info "  Key:          configured (value hidden)"
echo ""

# ── Stop previous container if running ────────────────────────────────
if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
  info "Stopping previous ${CONTAINER_NAME}..."
  docker rm -f "$CONTAINER_NAME" >/dev/null 2>&1 || true
fi

# ── Build ─────────────────────────────────────────────────────────────
docker build \
  --build-arg REACT_APP_EMILY_URL="$EMILY_URL" \
  --build-arg REACT_APP_EMILY_KEY="$EMILY_KEY" \
  --build-arg EMILY_HERMES_KEY="$EMILY_HERMES_KEY" \
  -t "$IMAGE_NAME" \
  frontend/

# ── Run ───────────────────────────────────────────────────────────────
docker run -d \
  --name "$CONTAINER_NAME" \
  -p "127.0.0.1:${PORT}:80" \
  --restart unless-stopped \
  "$IMAGE_NAME"

echo ""
info "EcoSeek frontend is running!"
info ""
info "  Open: http://localhost:${PORT}"
info ""
info "  Emily (your ecological AI assistant) is ready."
info "  Chat is proxied by nginx to the Emily gateway on :8642 with a"
info "  server-side key — no broker involved, browser never sees a key."
info ""
info "Commands:"
info "  Stop:    docker stop ${CONTAINER_NAME}"
info "  Logs:    docker logs -f ${CONTAINER_NAME}"
info "  Restart: docker restart ${CONTAINER_NAME}"
info "  Rebuild: bash frontend-start.sh"