#!/usr/bin/env bash
# EcoSeek one-command setup.
# Works on Linux, macOS, and Windows (WSL).
#
# Usage:
#   bash setup.sh                            # interactive, prompts for DeepSeek key
#   DEEPSEEK_API_KEY=sk-xxx bash setup.sh    # non-interactive (BYOK)
#
# What it does:
#   1. Checks prerequisites (git, docker, docker compose v2)
#   2. Generates / updates .env with all the variables docker-compose.yml expects
#   3. Generates config.ini for the EcoSeek UI / orchestrator
#   4. Clones dependency repos into .repos/ (uses YOUR git auth)
#
# After this script, start the stack with:
#   docker compose up -d
#
# No Node.js, Python, or npm required on the host — just Git + Docker.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { printf "${GREEN}[ecoseek]${NC} %s\n" "$*"; }
warn()  { printf "${YELLOW}[ecoseek]${NC} %s\n" "$*"; }
error() { printf "${RED}[ecoseek]${NC} %s\n" "$*" >&2; }

# Never print the value of an env var whose name contains a secret marker.
is_secret_name() {
  case "$1" in
    *KEY*|*TOKEN*|*SECRET*|*PASSWORD*) return 0 ;;
    *) return 1 ;;
  esac
}

# ── Prerequisites ─────────────────────────────────────────────────────────
check_cmd() {
  if ! command -v "$1" &>/dev/null; then
    error "Required: $1 is not installed."
    error "$2"
    exit 1
  fi
}

check_cmd git    "Install git: https://git-scm.com/downloads"
check_cmd docker "Install Docker Desktop: https://docs.docker.com/get-docker/"

if ! docker compose version &>/dev/null; then
  error "docker compose (v2 plugin) not found."
  error "Update Docker Desktop or install: https://docs.docker.com/compose/install/"
  exit 1
fi

if ! docker info &>/dev/null 2>&1; then
  error "Docker daemon is not running. Start Docker Desktop and try again."
  exit 1
fi

# ── DeepSeek API key (BYOK — optional) ────────────────────────────────────
if [ -z "${DEEPSEEK_API_KEY:-}" ]; then
  echo ""
  info "No DEEPSEEK_API_KEY found in environment."
  info "Get your key at: https://platform.deepseek.com/api_keys"
  echo ""
  printf "${GREEN}[ecoseek]${NC} Enter your DeepSeek API key (or press Enter to skip): "
  read -r DEEPSEEK_API_KEY
  if [ -z "$DEEPSEEK_API_KEY" ]; then
    warn "No API key provided. EcoSeek will run in local-only mode (Ollama)."
  fi
fi
export DEEPSEEK_API_KEY

# ── Generate / update .env ────────────────────────────────────────────────
# Defaults that docker-compose.yml expects.
ECOSEEK_UI_PORT="${ECOSEEK_UI_PORT:-3000}"
AGENTICPLUG_PORT="${AGENTICPLUG_PORT:-8080}"
ECOAGENT_PORT="${ECOAGENT_PORT:-8000}"
OLLAMA_PORT="${OLLAMA_PORT:-11434}"
OLLAMA_MODEL="${OLLAMA_MODEL:-ecocoder}"
ECOSEEK_AAR_ENABLED="${ECOSEEK_AAR_ENABLED:-false}"
ECOSEEK_JUDGE_MODEL="${ECOSEEK_JUDGE_MODEL:-auto}"
PHOENIX_ENDPOINT="${PHOENIX_ENDPOINT:-http://phoenix:6006}"
PHOENIX_PROJECT_NAME="${PHOENIX_PROJECT_NAME:-ecoseek}"

OVERWRITE=1
if [ -f .env ]; then
  echo ""
  warn ".env already exists at $(pwd)/.env"
  printf "${GREEN}[ecoseek]${NC} Overwrite it with the latest defaults? [y/N]: "
  read -r REPLY
  case "$REPLY" in
    [yY]|[yY][eE][sS]) OVERWRITE=1 ;;
    *) OVERWRITE=0 ;;
  esac
fi

if [ "$OVERWRITE" -eq 1 ]; then
  # Write atomically to avoid leaving a half-written .env on error.
  TMP_ENV="$(mktemp .env.XXXXXX)"
  {
    echo "# Generated by setup.sh — local only, do not commit"
    echo ""
    echo "# Ports"
    echo "ECOSEEK_UI_PORT=${ECOSEEK_UI_PORT}"
    echo "AGENTICPLUG_PORT=${AGENTICPLUG_PORT}"
    echo "ECOAGENT_PORT=${ECOAGENT_PORT}"
    echo "OLLAMA_PORT=${OLLAMA_PORT}"
    echo ""
    echo "# Local model"
    echo "OLLAMA_MODEL=${OLLAMA_MODEL}"
    echo ""
    echo "# Adaptive Autonomous Retrieval"
    echo "ECOSEEK_AAR_ENABLED=${ECOSEEK_AAR_ENABLED}"
    echo "ECOSEEK_JUDGE_MODEL=${ECOSEEK_JUDGE_MODEL}"
    echo ""
    echo "# Phoenix observability (optional profile)"
    echo "PHOENIX_ENDPOINT=${PHOENIX_ENDPOINT}"
    echo "PHOENIX_PROJECT_NAME=${PHOENIX_PROJECT_NAME}"
    echo ""
    echo "# BYOK — empty by default; fill in to use DeepSeek cloud"
    echo "DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY:-}"
  } > "$TMP_ENV"
  mv "$TMP_ENV" .env
  chmod 600 .env || true
  info ".env written to $(pwd)/.env (git-ignored, local only)"
else
  info "Keeping existing .env unchanged"
fi

# ── Generate config.ini ──────────────────────────────────────────────────
# The UI / orchestrator reads config.ini at startup. Use Docker networking
# hostnames (e.g. ollama:11434, agenticplug:${AGENTICPLUG_PORT}) so the
# containers can find each other without host networking.
if [ -n "${DEEPSEEK_API_KEY:-}" ]; then
  PROVIDER_NAME="deepseek"
  PROVIDER_MODEL="deepseek-chat"
  PROVIDER_ADDRESS="https://api.deepseek.com"
  IS_LOCAL="False"
  info "LLM provider: DeepSeek API (cloud, BYOK)"
else
  PROVIDER_NAME="ollama"
  PROVIDER_MODEL="${OLLAMA_MODEL}"
  PROVIDER_ADDRESS="http://ollama:${OLLAMA_PORT}"
  IS_LOCAL="True"
  info "LLM provider: Ollama (local) — pull the model with:"
  info "  docker compose exec ollama ollama pull ${OLLAMA_MODEL}"
fi

cat > config.ini <<EOF
[MAIN]
is_local = ${IS_LOCAL}
provider_name = ${PROVIDER_NAME}
provider_model = ${PROVIDER_MODEL}
provider_server_address = ${PROVIDER_ADDRESS}
agent_name = EcoSeek
recover_last_session = False
save_session = False
speak = False
listen = False
jarvis_personality = False
personality = ecoseek
temperature = 0.3
top_p = 0.9
languages = en
[BROWSER]
headless_browser = True
stealth_mode = False
EOF
info "Generated config.ini (provider: ${PROVIDER_NAME})"

# ── Clone dependency repos ────────────────────────────────────────────────
clone_repo() {
  local repo_url="$1"
  local dest="$2"
  if [ -d "$dest/.git" ]; then
    info "Updating $dest ..."
    git -C "$dest" pull --ff-only 2>/dev/null || warn "Could not update $dest (non-fatal)"
  else
    info "Cloning $repo_url into $dest ..."
    git clone --depth 1 "$repo_url" "$dest"
  fi
}

mkdir -p .repos
clone_repo "https://github.com/alrobles/agenticplug.git" ".repos/agenticplug"
clone_repo "https://github.com/alrobles/agenticSeek.git"  ".repos/agenticSeek"
clone_repo "https://github.com/alrobles/ecoagent.git"     ".repos/ecoagent"

# ── Summary ───────────────────────────────────────────────────────────────
echo ""
info "Setup complete. Local URLs after 'docker compose up -d':"
printf "  %-25s %s\n" "EcoSeek UI:"          "http://localhost:${ECOSEEK_UI_PORT}"
printf "  %-25s %s\n" "AgenticPlug gateway:" "http://localhost:${AGENTICPLUG_PORT}"
printf "  %-25s %s\n" "EcoAgent tools:"      "http://localhost:${ECOAGENT_PORT}/v1/tools"
printf "  %-25s %s\n" "Ollama API:"          "http://localhost:${OLLAMA_PORT}"
printf "  %-25s %s\n" "Phoenix (optional):"  "http://localhost:6006  (--profile observability)"
echo ""
info "Selected model: OLLAMA_MODEL=${OLLAMA_MODEL}"
if [ -n "${DEEPSEEK_API_KEY:-}" ]; then
  info "DeepSeek BYOK: configured (value hidden)"
else
  info "DeepSeek BYOK: not set — running in local-only mode"
fi
if [ "${ECOSEEK_AAR_ENABLED}" = "true" ]; then
  info "AAR mode: ENABLED"
else
  info "AAR mode: disabled (set ECOSEEK_AAR_ENABLED=true to enable)"
fi
echo ""
info "Next steps:"
info "  1. docker compose up -d"
info "  2. Wait for services to become healthy (docker compose ps)"
info "  3. Open http://localhost:${ECOSEEK_UI_PORT}"
info "  4. Smoke test:  docs/smoke-test.md"
echo ""
info "To stop:    docker compose down"
info "Logs:       docker compose logs -f"
info "Rebuild:    bash setup.sh && docker compose up --build -d"

# Defensive: ensure we never echoed a secret-named variable in this script.
# (Static guard for future edits.)
if false; then
  for v in DEEPSEEK_API_KEY; do
    is_secret_name "$v" && true
  done
fi
