/**
 * Broker API client — dual-mode support for EcoSeek.
 *
 * Auth always goes through the broker (GitHub OAuth).
 * Chat goes to Emily local (if REACT_APP_EMILY_URL is set) or the broker.
 *
 * Modes:
 *   - Local Emily:  Auth via broker, chat via Emily at localhost:8642
 *   - Remote only:  Auth + chat both via broker → Hermes remote on reumanlab
 */

const BROKER_URL =
  process.env.REACT_APP_BROKER_URL || "https://broker.ecoseek.org";

/**
 * Emily local agent URL. When set, chat goes directly to Emily.
 * Auth still goes through the broker for GitHub OAuth security.
 */
const EMILY_URL = process.env.REACT_APP_EMILY_URL || "";

const IS_LOCAL_EMILY = Boolean(EMILY_URL);

/**
 * Shared API key for authenticating with Emily local.
 * Generated by emily-start.sh and baked into the frontend at build time.
 * Hermes requires this when the API server binds to 0.0.0.0 (Docker).
 */
const EMILY_KEY = process.env.REACT_APP_EMILY_KEY || "";

/** The endpoint to send chat completions to. */
const CHAT_URL = IS_LOCAL_EMILY ? EMILY_URL : BROKER_URL;

// ── Session helpers ────────────────────────────────────────────────────

const SESSION_KEY = "ecoseek_session";

export function getSession() {
  try {
    const raw = localStorage.getItem(SESSION_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

export function saveSession(sessionId, user) {
  localStorage.setItem(
    SESSION_KEY,
    JSON.stringify({ session_id: sessionId, user, broker_url: BROKER_URL })
  );
}

export function clearSession() {
  localStorage.removeItem(SESSION_KEY);
}

export function getSessionId() {
  return getSession()?.session_id || null;
}

// ── Auth (always via broker — GitHub OAuth) ────────────────────────────

/**
 * Start GitHub OAuth via the broker. Works the same in both modes.
 */
export function startLogin(returnTo) {
  const url = `${BROKER_URL}/auth/github/start?return_to=${encodeURIComponent(
    returnTo || window.location.origin + "/callback"
  )}`;
  window.location.href = url;
}

/**
 * Fetch current user identity via broker GET /v1/me.
 */
export async function fetchMe() {
  const sid = getSessionId();
  if (!sid) return null;
  try {
    const res = await fetch(`${BROKER_URL}/v1/me`, {
      headers: { Authorization: `Bearer ${sid}` },
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

// ── Health ──────────────────────────────────────────────────────────────

export async function checkHealth() {
  try {
    // Check Emily local health if configured, otherwise check broker
    if (IS_LOCAL_EMILY) {
      const res = await fetch(`${EMILY_URL}/health`);
      return res.ok;
    }
    const res = await fetch(`${BROKER_URL}/healthz`);
    return res.ok;
  } catch {
    return false;
  }
}

const HERMES_REMOTE_URL =
  process.env.REACT_APP_HERMES_REMOTE_URL || "https://hermes.ecoseek.org";

/**
 * Check Hermes remote health via nginx proxy (avoids CORS).
 * In Docker, the frontend's nginx proxies /api/hermes-health → hermes.ecoseek.org/health.
 * In dev mode, falls back to direct fetch (will fail on CORS but won't crash).
 */
export async function checkRemoteHealth() {
  try {
    // Use nginx proxy in production, direct URL in dev
    const proxyUrl = "/api/hermes-health";
    const res = await fetch(proxyUrl);
    if (!res.ok) return null;
    return await res.json();
  } catch {
    // Fallback: try direct (works from curl, not browsers due to CORS)
    try {
      const res = await fetch(`${HERMES_REMOTE_URL}/health`);
      if (!res.ok) return null;
      return await res.json();
    } catch {
      return null;
    }
  }
}

// ── Emily persona ──────────────────────────────────────────────────────

const EMILY_SYSTEM_PROMPT = `You are Emily, an expert ecological scientist and AI assistant for EcoSeek.

Your specialties include:
- Ecological niche modeling and species distribution models (SDMs)
- Biogeography and macroecology
- GBIF biodiversity data analysis
- Phylogenetic analysis and comparative methods
- Population ecology and stochastic demography
- R programming for ecological analysis (vegan, terra, dismo, ape, picante)
- Spatial analysis and GIS

Personality:
- You are warm, knowledgeable, and passionate about biodiversity.
- You explain complex ecological concepts clearly and accessibly.
- You always suggest reproducible workflows and cite data sources.
- When appropriate, you provide R or Python code snippets.
- You encourage best practices in open science and data provenance.
- You know about GBIF, WoRMS, IUCN, and other biodiversity databases.

Always introduce yourself as Emily on the first interaction. Keep responses focused and scientifically rigorous.`;

// ── Chat completions ───────────────────────────────────────────────────

/**
 * Send a chat completion request.
 *
 * - Local Emily: talks to Emily at EMILY_URL (personality in Hermes config)
 * - Remote: talks to broker (prepends Emily system prompt)
 *
 * Auth token (session_id from GitHub OAuth) is sent to both.
 * Emily local validates via API_SERVER_KEY; broker validates via session store.
 *
 * @param {Array} messages  OpenAI-style messages array
 * @param {string} model    Model name (local Emily uses Hermes config default)
 * @returns {Promise<object>} Parsed response body
 */
export async function chatCompletion(messages, model = "hermes") {
  const sid = getSessionId();
  if (!sid) throw new Error("Not logged in");

  const fullMessages = IS_LOCAL_EMILY
    ? messages
    : [{ role: "system", content: EMILY_SYSTEM_PROMPT }, ...messages];

  const authToken = IS_LOCAL_EMILY && EMILY_KEY ? EMILY_KEY : sid;

  const res = await fetch(`${CHAT_URL}/v1/chat/completions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${authToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ model, messages: fullMessages }),
  });

  const body = await res.json();
  if (!res.ok) {
    const msg = body?.error?.message || body?.error || `HTTP ${res.status}`;
    throw new Error(msg);
  }
  return body;
}

/**
 * Streaming chat completion via SSE.
 *
 * Sends `stream: true` to the OpenAI-compatible endpoint and fires callbacks
 * as tokens, tool calls, and reasoning chunks arrive.
 *
 * @param {Array}    messages    OpenAI-style messages array
 * @param {object}   callbacks   Event handlers:
 *   - onToken(text)            — content delta
 *   - onReasoning(text)        — reasoning_content delta
 *   - onToolCallStart(tool)    — tool call begins {name, id, arguments}
 *   - onToolCallDelta(id, arg) — streamed function arguments
 *   - onToolCallDone(result)   — tool result returned (from non-streaming follow-up)
 *   - onDone(fullResponse)     — stream finished
 *   - onError(error)           — stream error
 * @param {string}   model       Model name
 * @param {AbortSignal} signal   Optional abort signal
 */
export async function chatCompletionStream(
  messages,
  callbacks = {},
  model = "hermes",
  signal = null,
) {
  const sid = getSessionId();
  if (!sid) throw new Error("Not logged in");

  const fullMessages = IS_LOCAL_EMILY
    ? messages
    : [{ role: "system", content: EMILY_SYSTEM_PROMPT }, ...messages];

  const authToken = IS_LOCAL_EMILY && EMILY_KEY ? EMILY_KEY : sid;

  const res = await fetch(`${CHAT_URL}/v1/chat/completions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${authToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ model, messages: fullMessages, stream: true }),
    signal,
  });

  if (!res.ok) {
    let errMsg = `HTTP ${res.status}`;
    try {
      const body = await res.json();
      errMsg = body?.error?.message || body?.error || errMsg;
    } catch { /* ignore parse errors */ }
    throw new Error(errMsg);
  }

  const reader = res.body.getReader();
  const decoder = new TextDecoder();
  let buffer = "";
  let fullContent = "";
  let fullReasoning = "";
  let modelUsed = model;
  let finishReason = null;
  const toolCalls = new Map();

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split("\n");
      buffer = lines.pop() || "";

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || trimmed === "data: [DONE]") {
          if (trimmed === "data: [DONE]") {
            callbacks.onDone?.({
              content: fullContent,
              reasoning: fullReasoning || null,
              model: modelUsed,
              finishReason,
              toolCalls: Array.from(toolCalls.values()),
            });
          }
          continue;
        }

        if (!trimmed.startsWith("data: ")) continue;

        let chunk;
        try {
          chunk = JSON.parse(trimmed.slice(6));
        } catch {
          continue;
        }

        if (chunk.model) modelUsed = chunk.model;

        const delta = chunk.choices?.[0]?.delta;
        if (!delta) continue;

        finishReason = chunk.choices[0].finish_reason || finishReason;

        // Content tokens
        if (delta.content) {
          fullContent += delta.content;
          callbacks.onToken?.(delta.content);
        }

        // Reasoning tokens (DeepSeek extended field)
        if (delta.reasoning_content) {
          fullReasoning += delta.reasoning_content;
          callbacks.onReasoning?.(delta.reasoning_content);
        }

        // Tool calls — streamed incrementally
        if (delta.tool_calls) {
          for (const tc of delta.tool_calls) {
            const idx = tc.index ?? 0;
            if (!toolCalls.has(idx)) {
              toolCalls.set(idx, {
                id: tc.id || `call_${idx}`,
                name: tc.function?.name || "",
                arguments: "",
              });
              if (tc.function?.name) {
                callbacks.onToolCallStart?.({
                  id: tc.id || `call_${idx}`,
                  name: tc.function.name,
                  index: idx,
                });
              }
            }
            const existing = toolCalls.get(idx);
            if (tc.function?.name && !existing.name) {
              existing.name = tc.function.name;
              callbacks.onToolCallStart?.({
                id: existing.id,
                name: existing.name,
                index: idx,
              });
            }
            if (tc.function?.arguments) {
              existing.arguments += tc.function.arguments;
              callbacks.onToolCallDelta?.(existing.id, tc.function.arguments);
            }
          }
        }
      }
    }
  } catch (err) {
    if (err.name !== "AbortError") {
      callbacks.onError?.(err);
      throw err;
    }
  }

  // If we never got [DONE] (e.g. connection closed), still fire onDone
  if (fullContent || fullReasoning) {
    callbacks.onDone?.({
      content: fullContent,
      reasoning: fullReasoning || null,
      model: modelUsed,
      finishReason,
      toolCalls: Array.from(toolCalls.values()),
    });
  }
}

export { BROKER_URL, EMILY_URL, CHAT_URL, IS_LOCAL_EMILY, HERMES_REMOTE_URL };
