/**
 * Broker API client — dual-mode support for EcoSeek.
 *
 * Auth always goes through the broker (GitHub OAuth).
 * Chat goes to Emily local (if REACT_APP_EMILY_URL is set) or the broker.
 *
 * Modes:
 *   - Local Emily:  Auth via broker, chat via Emily at localhost:8642
 *   - Remote only:  Auth + chat both via broker → Hermes remote on reumanlab
 */

const BROKER_URL =
  process.env.REACT_APP_BROKER_URL || "https://broker.ecoseek.org";

/**
 * Emily local agent URL. When set, chat goes directly to Emily.
 * Auth still goes through the broker for GitHub OAuth security.
 */
const EMILY_URL = process.env.REACT_APP_EMILY_URL || "";

const IS_LOCAL_EMILY = Boolean(EMILY_URL);

/**
 * Shared API key for authenticating with Emily local.
 * Generated by emily-start.sh and baked into the frontend at build time.
 * Hermes requires this when the API server binds to 0.0.0.0 (Docker).
 */
const EMILY_KEY = process.env.REACT_APP_EMILY_KEY || "";

/** The endpoint to send chat completions to. */
const CHAT_URL = IS_LOCAL_EMILY ? EMILY_URL : BROKER_URL;

// ── Session helpers ────────────────────────────────────────────────────

const SESSION_KEY = "ecoseek_session";

export function getSession() {
  try {
    const raw = localStorage.getItem(SESSION_KEY);
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

export function saveSession(sessionId, user) {
  localStorage.setItem(
    SESSION_KEY,
    JSON.stringify({ session_id: sessionId, user, broker_url: BROKER_URL })
  );
}

export function clearSession() {
  localStorage.removeItem(SESSION_KEY);
}

export function getSessionId() {
  return getSession()?.session_id || null;
}

// ── Auth (always via broker — GitHub OAuth) ────────────────────────────

/**
 * Start GitHub OAuth via the broker. Works the same in both modes.
 */
export function startLogin(returnTo) {
  const url = `${BROKER_URL}/auth/github/start?return_to=${encodeURIComponent(
    returnTo || window.location.origin + "/callback"
  )}`;
  window.location.href = url;
}

/**
 * Fetch current user identity via broker GET /v1/me.
 */
export async function fetchMe() {
  const sid = getSessionId();
  if (!sid) return null;
  try {
    const res = await fetch(`${BROKER_URL}/v1/me`, {
      headers: { Authorization: `Bearer ${sid}` },
    });
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

// ── Health ──────────────────────────────────────────────────────────────

export async function checkHealth() {
  try {
    // Check Emily local health if configured, otherwise check broker
    if (IS_LOCAL_EMILY) {
      const res = await fetch(`${EMILY_URL}/health`);
      return res.ok;
    }
    const res = await fetch(`${BROKER_URL}/healthz`);
    return res.ok;
  } catch {
    return false;
  }
}

const HERMES_REMOTE_URL =
  process.env.REACT_APP_HERMES_REMOTE_URL || "https://hermes.ecoseek.org";

export async function checkRemoteHealth() {
  try {
    const res = await fetch(`${HERMES_REMOTE_URL}/health`);
    if (!res.ok) return null;
    return await res.json();
  } catch {
    return null;
  }
}

// ── Emily persona ──────────────────────────────────────────────────────

const EMILY_SYSTEM_PROMPT = `You are Emily, an expert ecological scientist and AI assistant for EcoSeek.

Your specialties include:
- Ecological niche modeling and species distribution models (SDMs)
- Biogeography and macroecology
- GBIF biodiversity data analysis
- Phylogenetic analysis and comparative methods
- Population ecology and stochastic demography
- R programming for ecological analysis (vegan, terra, dismo, ape, picante)
- Spatial analysis and GIS

Personality:
- You are warm, knowledgeable, and passionate about biodiversity.
- You explain complex ecological concepts clearly and accessibly.
- You always suggest reproducible workflows and cite data sources.
- When appropriate, you provide R or Python code snippets.
- You encourage best practices in open science and data provenance.
- You know about GBIF, WoRMS, IUCN, and other biodiversity databases.

Always introduce yourself as Emily on the first interaction. Keep responses focused and scientifically rigorous.`;

// ── Chat completions ───────────────────────────────────────────────────

/**
 * Send a chat completion request.
 *
 * - Local Emily: talks to Emily at EMILY_URL (personality in Hermes config)
 * - Remote: talks to broker (prepends Emily system prompt)
 *
 * Auth token (session_id from GitHub OAuth) is sent to both.
 * Emily local validates via API_SERVER_KEY; broker validates via session store.
 *
 * @param {Array} messages  OpenAI-style messages array
 * @param {string} model    Model name (local Emily uses Hermes config default)
 * @returns {Promise<object>} Parsed response body
 */
export async function chatCompletion(messages, model = "hermes") {
  const sid = getSessionId();
  if (!sid) throw new Error("Not logged in");

  // Local Emily has personality baked into Hermes config — no system prompt needed.
  // Remote broker needs the system prompt injected by the frontend.
  const fullMessages = IS_LOCAL_EMILY
    ? messages
    : [{ role: "system", content: EMILY_SYSTEM_PROMPT }, ...messages];

  // Local Emily uses a shared API key (generated by emily-start.sh).
  // Remote broker uses the OAuth session token.
  const authToken = IS_LOCAL_EMILY && EMILY_KEY ? EMILY_KEY : sid;

  const res = await fetch(`${CHAT_URL}/v1/chat/completions`, {
    method: "POST",
    headers: {
      Authorization: `Bearer ${authToken}`,
      "Content-Type": "application/json",
    },
    body: JSON.stringify({ model, messages: fullMessages }),
  });

  const body = await res.json();
  if (!res.ok) {
    const msg = body?.error?.message || body?.error || `HTTP ${res.status}`;
    throw new Error(msg);
  }
  return body;
}

export { BROKER_URL, EMILY_URL, CHAT_URL, IS_LOCAL_EMILY, HERMES_REMOTE_URL };
