"""LACS — Literature Abstract Classification System integration.

Provides domain-specific relevance scoring for scientific literature using
Positive-Unlabeled (PU) learning via the LACS/xplus R packages on the HPC
cluster.  Two execution modes:

  1. **Remote (cluster)** — sends abstracts to Hermes → R execution in the
     geospatial SIF.  Requires a pre-trained ``.rds`` model on the cluster.
  2. **Local (lightweight)** — uses a keyword-frequency heuristic when the
     cluster is unreachable.  Fast but less accurate.

Design follows alrobles/lacs (validate → vocabulary → DTM → PLUS) and the
dissertation Chapter 2 (LACS: A Lightweight Open-Source System for
Domain-Specific Scientific Literature Classification).

Cluster paths:
  - Models:     /home/a474r867/work/lacs_models/<domain>.rds
  - SIF:        /home/a474r867/geospatial-rserver/geospatial_latest.sif
  - R library:  ~/R/library

Env vars:
  LACS_ENABLED         — enable LACS scoring (default: true)
  LACS_DEFAULT_DOMAIN  — default model domain (default: host-parasite)
  LACS_THRESHOLD       — minimum score to consider relevant (default: 0.5)
"""
from __future__ import annotations

import json
import logging
import os
import urllib.error
import urllib.request

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

_LACS_ENABLED = os.environ.get("LACS_ENABLED", "true").lower() in ("true", "1", "yes")
_DEFAULT_DOMAIN = os.environ.get("LACS_DEFAULT_DOMAIN", "host-parasite")
_LACS_THRESHOLD = float(os.environ.get("LACS_THRESHOLD", "0.5"))

_HERMES_URL = os.environ.get("HERMES_REMOTE_URL", "https://hermes.ecoseek.org").rstrip("/")
_API_KEY = os.environ.get("HERMES_ECOSEEK_API_KEY", "")
_TIMEOUT = int(os.environ.get("LACS_TIMEOUT", "30"))

# Cluster paths
_MODELS_DIR = "/home/a474r867/work/lacs_models"
_SIF_PATH = "/home/a474r867/geospatial-rserver/geospatial_latest.sif"
_R_LIB = "~/R/library"

# Available pre-trained domains
AVAILABLE_DOMAINS = {
    "host-parasite": "Host-parasite ecological interactions (GMPD + ZOVER training set)",
    "niche-modeling": "Species distribution & niche modeling literature",
    "biodiversity": "General biodiversity & ecology literature",
}

# ---------------------------------------------------------------------------
# Local fallback: keyword-frequency heuristic
# ---------------------------------------------------------------------------

_DOMAIN_KEYWORDS: dict[str, list[str]] = {
    "host-parasite": [
        "host", "parasite", "pathogen", "virus", "zoonotic", "spillover",
        "reservoir", "vector", "infection", "transmission", "susceptibility",
        "hantavirus", "rodent", "bat", "mammal", "interaction", "disease",
        "endemic", "epidemic", "wildlife", "ecological", "phylogenetic",
    ],
    "niche-modeling": [
        "niche", "distribution", "bioclimatic", "chelsa", "maxent", "gbif",
        "occurrence", "suitability", "ellipsoid", "climate", "species",
        "habitat", "modeling", "projection", "environmental", "raster",
        "ecoregion", "presence", "absence", "sdm",
    ],
    "biodiversity": [
        "biodiversity", "species", "richness", "diversity", "conservation",
        "ecosystem", "community", "abundance", "phylogenetic", "trait",
        "functional", "ecological", "habitat", "population", "evolution",
        "taxonomy", "morphological", "genetic",
    ],
}


def _score_local(abstract: str, domain: str) -> float:
    """Lightweight keyword-frequency heuristic (0.0-1.0).

    Used as fallback when the cluster is unreachable.
    """
    if not abstract or len(abstract) < 20:
        return 0.0

    keywords = _DOMAIN_KEYWORDS.get(domain, _DOMAIN_KEYWORDS["host-parasite"])
    text_lower = abstract.lower()
    hits = sum(1 for kw in keywords if kw in text_lower)
    return min(hits / max(len(keywords) * 0.4, 1), 1.0)


# ---------------------------------------------------------------------------
# Remote scoring via Hermes → R execution
# ---------------------------------------------------------------------------

def _build_r_scoring_script(abstracts: list[str], domain: str) -> str:
    """Generate R code that loads a LACS model and scores abstracts."""
    model_path = f"{_MODELS_DIR}/{domain}.rds"

    abstracts_json = json.dumps(abstracts, ensure_ascii=False)

    return f"""
# LACS scoring script — auto-generated by Emily
suppressMessages({{
  library(lacs)
  library(jsonlite)
}})

model_path <- "{model_path}"
if (!file.exists(model_path)) {{
  cat(toJSON(list(error = paste("Model not found:", model_path)), auto_unbox = TRUE))
  quit(status = 0)
}}

lacs_model <- readRDS(model_path)

abstracts <- fromJSON('{abstracts_json}')

scores <- tryCatch({{
  predictions <- predict(lacs_model, abstracts)
  as.numeric(predictions)
}}, error = function(e) {{
  # Fallback: score each abstract individually
  sapply(abstracts, function(a) {{
    tryCatch({{
      newX <- get_dtm(
        get_abstracts(data.frame(
          doi = "temp", title = "temp",
          abstract = a, class = "unknown",
          stringsAsFactors = FALSE
        )),
        lacs_model$vocabulary,
        tf_idf = TRUE
      )
      pred <- predict(lacs_model$plus$fit.pi,
                      newx = newX,
                      s = "lambda.min",
                      type = "response")
      as.numeric(pred[1, 1])
    }}, error = function(e2) 0.0)
  }})
}})

result <- list(
  scores = scores,
  domain = "{domain}",
  model_path = model_path,
  n_scored = length(scores)
)
cat(toJSON(result, auto_unbox = TRUE))
"""


def score_abstracts_remote(
    abstracts: list[str],
    domain: str = _DEFAULT_DOMAIN,
) -> list[float]:
    """Score abstracts using the cluster LACS model via Hermes.

    Returns a list of scores (0.0-1.0) for each abstract.
    """
    if not _API_KEY:
        logger.warning("No Hermes API key — falling back to local scoring")
        return [_score_local(a, domain) for a in abstracts]

    r_code = _build_r_scoring_script(abstracts, domain)

    payload = {
        "model": "hermes-agent",
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are executing an R script on the HPC cluster. "
                    "Run the following R code using the geospatial SIF container "
                    "and return ONLY the JSON output. Do not add commentary."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Execute this R code on the cluster using:\n"
                    f"apptainer exec --bind ~/R/library:/usr/local/lib/R/site-library "
                    f"{_SIF_PATH} Rscript -e '<code>'\n\n"
                    f"R code:\n```r\n{r_code}\n```\n\n"
                    f"Return only the JSON output from the script."
                ),
            },
        ],
    }

    try:
        from .http_client import http_post_json
        result = http_post_json(
            f"{_HERMES_URL}/v1/chat/completions",
            payload,
            headers={"Authorization": f"Bearer {_API_KEY}"},
            timeout=_TIMEOUT,
        )

        content = result.get("choices", [{}])[0].get("message", {}).get("content", "")

        # Try to extract JSON from the response
        try:
            # Look for JSON in the response
            json_match = _extract_json(content)
            if json_match and "scores" in json_match:
                scores = json_match["scores"]
                if isinstance(scores, list) and len(scores) == len(abstracts):
                    return [float(s) for s in scores]
        except (json.JSONDecodeError, ValueError, TypeError):
            pass

        logger.warning("Could not parse LACS scores from Hermes response; using local fallback")
        return [_score_local(a, domain) for a in abstracts]

    except Exception as exc:
        logger.warning("Hermes LACS scoring failed: %s; using local fallback", exc)
        return [_score_local(a, domain) for a in abstracts]


def _extract_json(text: str) -> dict | None:
    """Extract a JSON object from mixed text (LLM response may have wrapping)."""
    import re
    # Try the full text first
    try:
        return json.loads(text)
    except (json.JSONDecodeError, ValueError):
        pass

    # Try to find JSON in code blocks
    code_block = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", text, re.DOTALL)
    if code_block:
        try:
            return json.loads(code_block.group(1))
        except (json.JSONDecodeError, ValueError):
            pass

    # Try to find a JSON object anywhere
    brace = text.find("{")
    if brace >= 0:
        depth = 0
        for i, ch in enumerate(text[brace:], start=brace):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
            if depth == 0:
                try:
                    return json.loads(text[brace : i + 1])
                except (json.JSONDecodeError, ValueError):
                    break
    return None


# ---------------------------------------------------------------------------
# Public API: classify literature
# ---------------------------------------------------------------------------

def classify_abstracts(
    abstracts: list[str],
    domain: str = _DEFAULT_DOMAIN,
    use_cluster: bool = True,
) -> list[dict]:
    """Classify a list of abstracts by domain relevance.

    Parameters
    ----------
    abstracts : list[str]
        Text of each abstract to score.
    domain : str
        Pre-trained domain model to use (e.g., "host-parasite").
    use_cluster : bool
        If True, try cluster first; fallback to local heuristic.

    Returns
    -------
    list[dict]
        For each abstract: {"score": float, "relevant": bool, "method": str}
    """
    if not abstracts:
        return []

    if use_cluster and _LACS_ENABLED and _API_KEY:
        scores = score_abstracts_remote(abstracts, domain)
        method = "lacs_cluster"
    else:
        scores = [_score_local(a, domain) for a in abstracts]
        method = "keyword_heuristic"

    return [
        {
            "score": round(s, 4),
            "relevant": s >= _LACS_THRESHOLD,
            "method": method,
            "domain": domain,
        }
        for s in scores
    ]


def rerank_evidence(
    evidence_list: list[dict],
    domain: str = _DEFAULT_DOMAIN,
) -> list[dict]:
    """Re-rank retrieved evidence by LACS domain relevance.

    Modifies evidence dicts in-place: adds ``lacs_score`` and
    ``lacs_relevant`` fields, then re-sorts by combined score.

    Parameters
    ----------
    evidence_list : list[dict]
        Evidence dicts from retrieval (must have "abstract" key).
    domain : str
        LACS domain model.

    Returns
    -------
    list[dict]
        Same list, sorted by combined relevance score.
    """
    if not evidence_list:
        return evidence_list

    abstracts = [
        e.get("abstract", "") or e.get("title", "")
        for e in evidence_list
    ]

    classifications = classify_abstracts(abstracts, domain=domain)

    for ev, cls in zip(evidence_list, classifications):
        ev["lacs_score"] = cls["score"]
        ev["lacs_relevant"] = cls["relevant"]
        ev["lacs_method"] = cls["method"]
        ev["lacs_domain"] = cls["domain"]
        # Combined score: original confidence weighted by LACS relevance
        original_confidence = ev.get("confidence", 0.5)
        ev["combined_score"] = round(
            0.4 * original_confidence + 0.6 * cls["score"], 4
        )

    # Re-sort by combined score (highest first)
    evidence_list.sort(key=lambda e: e.get("combined_score", 0), reverse=True)

    return evidence_list


# ---------------------------------------------------------------------------
# Train a new LACS model (via Hermes → cluster)
# ---------------------------------------------------------------------------

def train_lacs_model(
    domain: str,
    positive_abstracts: list[dict],
    random_sample_size: int = 5000,
) -> dict:
    """Train a new LACS model on the cluster for a custom domain.

    Parameters
    ----------
    domain : str
        Name for the new domain model (e.g., "coral-bleaching").
    positive_abstracts : list[dict]
        List of known-positive papers, each with "doi", "title", "abstract".
    random_sample_size : int
        Number of random abstracts to use as unlabeled class.

    Returns
    -------
    dict
        Training result with model path, metrics, and status.
    """
    if not _API_KEY:
        return {"error": "Hermes API key required for model training", "success": False}

    if len(positive_abstracts) < 10:
        return {"error": "Need at least 10 positive abstracts to train a model", "success": False}

    model_path = f"{_MODELS_DIR}/{domain}.rds"

    # Build R training script
    abstracts_json = json.dumps(positive_abstracts, ensure_ascii=False)
    r_code = f"""
suppressMessages({{
  library(lacs)
  library(jsonlite)
}})

# Load positive abstracts
positive_papers <- fromJSON('{abstracts_json}')

# Create abstracts data frame with positive class
df_positive <- data.frame(
  doi = positive_papers$doi,
  title = positive_papers$title,
  abstract = positive_papers$abstract,
  class = "positive",
  stringsAsFactors = FALSE
)

# Generate random unlabeled abstracts from PubMed FTS5 index
# (or use built-in random sample if index not available)
pubmed_db <- "/home/a474r867/work/pubmed/index/pubmed_fts.db"
if (file.exists(pubmed_db)) {{
  con <- DBI::dbConnect(RSQLite::SQLite(), pubmed_db)
  random_abstracts <- DBI::dbGetQuery(con,
    "SELECT '' AS doi, title, abstract FROM pubmed_papers ORDER BY RANDOM() LIMIT {random_sample_size}")
  DBI::dbDisconnect(con)
}} else {{
  # Fallback: use lacs built-in sample data
  random_abstracts <- lacs::hp3_abstracts[sample(nrow(lacs::hp3_abstracts), min({random_sample_size}, nrow(lacs::hp3_abstracts))), ]
}}

df_unknown <- data.frame(
  doi = random_abstracts$doi,
  title = random_abstracts$title,
  abstract = random_abstracts$abstract,
  class = "unknown",
  stringsAsFactors = FALSE
)

# Combine and train
df_all <- rbind(df_positive, df_unknown)
abstracts_obj <- get_abstracts(df_all)

# Build vocabulary
vocab <- get_vocabulary(abstracts_obj,
  term_count_min = 5,
  doc_proportion_min = 0.01,
  doc_proportion_max = 0.5)

# Train LACS model
model <- lacs(abstracts_obj,
  vocabulary = vocab,
  alpha = 1,
  sample_use_time = 200,
  learning_rate = 1,
  qq = 0.001,
  tf_idf = TRUE)

# Save model
dir.create("{_MODELS_DIR}", recursive = TRUE, showWarnings = FALSE)
saveRDS(model, "{model_path}")

# Quick self-assessment
newX <- get_dtm(abstracts_obj, vocab, tf_idf = TRUE)
pred <- predict(model$plus$fit.pi, newx = newX, s = "lambda.min", type = "response")
y_true <- ifelse(df_all$class == "positive", 1, 0)
auc_val <- tryCatch({{
  pROC::auc(y_true, as.numeric(pred))
}}, error = function(e) NA)

result <- list(
  success = TRUE,
  model_path = "{model_path}",
  domain = "{domain}",
  n_positive = nrow(df_positive),
  n_unlabeled = nrow(df_unknown),
  vocab_size = nrow(vocab),
  auc = as.numeric(auc_val)
)
cat(toJSON(result, auto_unbox = TRUE))
"""

    payload = {
        "model": "hermes-agent",
        "messages": [
            {
                "role": "system",
                "content": (
                    "You are executing an R training script on the HPC cluster. "
                    "Run the R code using the geospatial SIF and return the JSON output."
                ),
            },
            {
                "role": "user",
                "content": (
                    f"Execute this R code on the cluster using:\n"
                    f"apptainer exec --bind ~/R/library:/usr/local/lib/R/site-library "
                    f"{_SIF_PATH} Rscript -e '<code>'\n\n"
                    f"R code:\n```r\n{r_code}\n```\n\n"
                    f"Return only the JSON output."
                ),
            },
        ],
    }

    try:
        from .http_client import http_post_json
        result = http_post_json(
            f"{_HERMES_URL}/v1/chat/completions",
            payload,
            headers={"Authorization": f"Bearer {_API_KEY}"},
            timeout=120,
        )

        content = result.get("choices", [{}])[0].get("message", {}).get("content", "")
        parsed = _extract_json(content)
        if parsed:
            return parsed
        return {"success": False, "error": "Could not parse training result", "raw": content[:500]}

    except Exception as exc:
        return {"success": False, "error": str(exc)[:200]}
